#!/usr/bin/env python3
"""Routing-manifest drift check.

Verifies that every skill present in skills/INDEX.json appears in the
routing manifest output (generated by scripts/routing-manifest.py).
A skill absent from the manifest is invisible to the router.

Also verifies that every indexed skill's SKILL.md resolves in at least
one overlay root (repo, deployed symlinks, private-skills). This closes
the "pass while unresolvable" hole where a skill is in the manifest text
but its SKILL.md doesn't exist anywhere.

skills/INDEX.json is a generated, untracked artifact (ADR untrack-generated-indexes).
If it is missing (fresh checkout), this script generates it first, then validates,
rather than failing on a missing tracked file.

Usage:
    python3 scripts/check-routing-drift.py
    python3 scripts/check-routing-drift.py --verbose

Exit codes:
    0 - All skills in INDEX.json appear in the routing manifest and resolve on disk
    1 - Index could not be produced, or one or more skills are absent/unresolvable
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_INDEX = REPO_ROOT / "skills" / "INDEX.json"
SKILLS_INDEX_GENERATOR = REPO_ROOT / "scripts" / "generate-skill-index.py"
MANIFEST_SCRIPT = REPO_ROOT / "scripts" / "routing-manifest.py"


def _ensure_skills_index() -> bool:
    """Ensure skills/INDEX.json exists, generating it if missing.

    INDEX.json is an untracked, generated artifact (ADR untrack-generated-indexes),
    so on a fresh checkout it may be absent. Generate it rather than failing.
    Returns True if the index is present (or was generated), False otherwise.
    """
    if SKILLS_INDEX.exists():
        return True
    if not SKILLS_INDEX_GENERATOR.exists():
        print(f"ERROR: {SKILLS_INDEX} missing and generator not found", file=sys.stderr)
        return False
    result = subprocess.run(
        [sys.executable, str(SKILLS_INDEX_GENERATOR)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        print(f"ERROR: failed to generate {SKILLS_INDEX}: {result.stderr}", file=sys.stderr)
        return False
    return SKILLS_INDEX.exists()


def _build_overlay_roots() -> list[Path]:
    """Build overlay roots for SKILL.md resolution (repo, deployed, private)."""
    candidates = [
        REPO_ROOT,
        Path.home() / ".claude",
    ]
    private_root = Path.home() / "private-skills"
    if private_root.is_dir():
        candidates.append(private_root)
    return [r for r in candidates if r.exists()]


def _resolve_skill_file(file_field: str, overlay_roots: list[Path]) -> bool:
    """Check if a skill file field resolves in any overlay root."""
    for root in overlay_roots:
        if (root / file_field).is_file():
            return True
    # Deployed symlink fallback: skills/<name>/SKILL.md -> ~/.claude/skills/<name>/SKILL.md
    parts = Path(file_field).parts
    if len(parts) >= 2 and parts[0] == "skills":
        deployed = Path.home() / ".claude" / "skills" / parts[1]
        if deployed.exists():
            real = deployed.resolve()
            if (real / "SKILL.md").is_file():
                return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verbose", action="store_true", help="Show all skills checked")
    args = parser.parse_args()

    if not _ensure_skills_index():
        return 1

    if not MANIFEST_SCRIPT.exists():
        print(f"ERROR: {MANIFEST_SCRIPT} not found", file=sys.stderr)
        return 1

    with open(SKILLS_INDEX) as f:
        idx = json.load(f)

    index_skills = sorted(idx.get("skills", {}).keys())

    # Generate manifest and check each skill appears
    result = subprocess.run(
        [sys.executable, str(MANIFEST_SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    if result.returncode != 0:
        print(f"ERROR: routing-manifest.py failed: {result.stderr}", file=sys.stderr)
        return 1

    manifest_text = result.stdout

    missing = [s for s in index_skills if s not in manifest_text]
    present = [s for s in index_skills if s in manifest_text]

    if args.verbose:
        print(f"Checked {len(index_skills)} skills against routing manifest")
        print(f"  Present: {len(present)}")
        print(f"  Missing: {len(missing)}")

    exit_code = 0

    if missing:
        print(f"\nFAIL: {len(missing)} skill(s) in INDEX.json absent from routing manifest:")
        for skill in missing:
            print(f"  {skill}")
        print("\nEnsure each skill has valid INDEX.json entry and routing-manifest.py renders it.")
        exit_code = 1

    # Check SKILL.md resolution: every indexed skill must resolve on disk
    # via at least one overlay root. Closes the "pass while unresolvable" hole.
    overlay_roots = _build_overlay_roots()
    unresolvable: list[str] = []
    for skill_name, entry in idx.get("skills", {}).items():
        if not isinstance(entry, dict):
            continue
        file_field = entry.get("file", "")
        if file_field and not _resolve_skill_file(file_field, overlay_roots):
            unresolvable.append(f"  {skill_name}: {file_field}")

    if unresolvable:
        print(f"\nFAIL: {len(unresolvable)} skill(s) indexed but SKILL.md unresolvable in any root:")
        for line in unresolvable:
            print(line)
        exit_code = 1
    elif args.verbose:
        print(f"\nPASS: all {len(index_skills)} indexed skills resolve on disk")

    if exit_code == 0 and args.verbose:
        print("\nPASS: routing manifest is in sync with INDEX.json")
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
