#!/usr/bin/env python3
"""Safe crontab management: backup, list, add, remove, verify.

Never pipes to `crontab -`. Always works through temp files.
Every mutation backs up the existing crontab first.

Usage:
    python3 scripts/crontab-manager.py list
    python3 scripts/crontab-manager.py backup
    python3 scripts/crontab-manager.py add --schedule "7 */12 * * *" --command "/path/to/script.sh --execute" --tag "reddit-automod"
    python3 scripts/crontab-manager.py remove --tag "reddit-automod"
    python3 scripts/crontab-manager.py verify --tag "reddit-automod"
    python3 scripts/crontab-manager.py generate-wrapper --name "reddit-automod" --prompt "Moderate r/sap" --workdir /home/user/repo --schedule "7 */12 * * *"
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

BACKUP_DIR = Path.home() / ".claude" / "crontab-backups"
TAG_PREFIX = "# claude-cron:"
WRAPPER_TEMPLATE = r"""#!/usr/bin/env bash
# {description}
# Generated by: python3 scripts/crontab-manager.py generate-wrapper
# Tag: {tag}
#
# Usage:
#   ./{script_name}              # Dry run (default)
#   ./{script_name} --execute    # Live mode
#
# Cron: {schedule}

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
WORK_DIR="{workdir}"
LOG_DIR="{logdir}"
LOCKFILE="/tmp/claude-cron-{tag}.lock"
MAX_BUDGET="${{MAX_BUDGET_USD:-{budget}}}"
EXECUTE=""

for arg in "$@"; do
    case "$arg" in
        --execute) EXECUTE="yes" ;;
        *) echo "Unknown arg: $arg" >&2; exit 1 ;;
    esac
done

mkdir -p "$LOG_DIR"

exec 9>"$LOCKFILE"
if ! flock -n 9; then
    echo "$(date -Iseconds) SKIP: another instance running" >> "$LOG_DIR/cron.log"
    exit 0
fi

echo "=== {name} run: $(date -Iseconds) ==="
echo "Mode: $( [ -n "$EXECUTE" ] && echo "live" || echo "dry-run" ) | Budget: \$$MAX_BUDGET"

PROMPT=$(cat <<'PROMPT_END'
{prompt}
PROMPT_END
)

[ -z "$EXECUTE" ] && PROMPT="$PROMPT

DRY RUN MODE: Show what you WOULD do, but do NOT execute any actions."

cd "$WORK_DIR"

{claude_path} -p "$PROMPT" \
    --output-format text \
    --permission-mode auto \
    --allowedTools "{allowed_tools}" \
    --max-budget-usd "$MAX_BUDGET" \
    --no-session-persistence \
    2>&1 | tee "$LOG_DIR/run-$(date +%Y%m%d-%H%M%S).log"

EXIT_CODE=${{PIPESTATUS[0]}}

echo ""
echo "=== Run complete: $(date -Iseconds) | exit: $EXIT_CODE ==="

exec 9>&-
rm -f "$LOCKFILE"
exit $EXIT_CODE
"""


def _get_crontab() -> str:
    """Read current crontab. Returns empty string if none."""
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    if result.returncode != 0:
        # "no crontab for user" is normal
        if "no crontab" in result.stderr.lower():
            return ""
        print(f"Error reading crontab: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def _install_crontab(content: str) -> None:
    """Install crontab from string via temp file. Never pipe."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".crontab", delete=False) as f:
        f.write(content)
        tmp_path = f.name

    try:
        result = subprocess.run(["crontab", tmp_path], capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Error installing crontab: {result.stderr}", file=sys.stderr)
            sys.exit(1)
    finally:
        os.unlink(tmp_path)


def _backup_crontab(content: str) -> Path:
    """Backup current crontab to timestamped file."""
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = BACKUP_DIR / f"crontab-{ts}.txt"
    backup_path.write_text(content)
    return backup_path


def _find_tag_lines(content: str, tag: str) -> tuple[int, int]:
    """Find start/end line indices for a tagged cron block.

    Returns (start, end) where end is exclusive.
    A block is: tag comment line + the cron command line after it.
    Returns (-1, -1) if not found.
    """
    lines = content.splitlines()
    marker = f"{TAG_PREFIX} {tag}"
    for i, line in enumerate(lines):
        if line.strip() == marker:
            # Block = tag line + next non-empty line (the cron entry)
            end = i + 1
            if end < len(lines) and lines[end].strip():
                end += 1
            return i, end
    return -1, -1


def _find_claude_path() -> str:
    """Find the claude CLI binary path."""
    result = subprocess.run(["which", "claude"], capture_output=True, text=True)
    if result.returncode == 0:
        return result.stdout.strip()
    # Common locations
    for candidate in [
        Path.home() / ".claude" / "local" / "claude",
        Path("/usr/local/bin/claude"),
        Path.home() / ".local" / "bin" / "claude",
    ]:
        if candidate.exists():
            return str(candidate)
    return "claude"  # fallback, let PATH resolve at runtime


# --- Commands ---


def cmd_list(args: argparse.Namespace) -> int:
    """List all crontab entries, highlighting claude-cron tagged ones."""
    content = _get_crontab()
    if not content.strip():
        print("Crontab is empty.")
        return 0

    lines = content.splitlines()
    claude_entries = []
    other_entries = []

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip().startswith(TAG_PREFIX):
            tag = line.strip().removeprefix(TAG_PREFIX).strip()
            cmd = lines[i + 1] if i + 1 < len(lines) else "(missing)"
            claude_entries.append({"tag": tag, "schedule": cmd, "line": i + 1})
            i += 2
        else:
            if line.strip() and not line.strip().startswith("#"):
                other_entries.append({"entry": line.strip(), "line": i + 1})
            i += 1

    if claude_entries:
        print("Claude Code cron jobs:")
        for e in claude_entries:
            print(f"  [{e['tag']}] {e['schedule']}")
    if other_entries:
        print(f"\nOther cron entries ({len(other_entries)}):")
        for e in other_entries:
            print(f"  {e['entry']}")
    if not claude_entries and not other_entries:
        print("No active cron entries (only comments/blanks).")

    return 0


def cmd_backup(args: argparse.Namespace) -> int:
    """Backup current crontab."""
    content = _get_crontab()
    if not content.strip():
        print("Crontab is empty, nothing to backup.")
        return 0
    path = _backup_crontab(content)
    print(f"Backed up to: {path}")
    return 0


def cmd_add(args: argparse.Namespace) -> int:
    """Add a tagged cron entry safely."""
    tag = args.tag
    schedule = args.schedule
    command = args.command

    # Validate cron schedule (5 fields)
    fields = schedule.split()
    if len(fields) != 5:
        print(
            f"Error: schedule must have 5 fields (got {len(fields)}): {schedule}",
            file=sys.stderr,
        )
        return 1

    content = _get_crontab()

    # Check for duplicate tag
    start, _ = _find_tag_lines(content, tag)
    if start != -1:
        print(f"Error: tag '{tag}' already exists. Remove it first.", file=sys.stderr)
        return 1

    # Backup before mutation
    if content.strip():
        backup = _backup_crontab(content)
        print(f"Backed up existing crontab: {backup}")

    # Build new entry
    entry = f"{TAG_PREFIX} {tag}\n{schedule} {command}\n"

    # Append
    if content and not content.endswith("\n"):
        content += "\n"
    content += entry

    if args.dry_run:
        print("DRY RUN — would add:")
        print(f"  {TAG_PREFIX} {tag}")
        print(f"  {schedule} {command}")
        return 0

    _install_crontab(content)

    # Verify
    new_content = _get_crontab()
    if tag in new_content:
        print(f"Added cron entry [{tag}]: {schedule} {command}")
        return 0
    else:
        print("Error: entry not found after install!", file=sys.stderr)
        return 1


def cmd_remove(args: argparse.Namespace) -> int:
    """Remove a tagged cron entry safely."""
    tag = args.tag
    content = _get_crontab()

    start, end = _find_tag_lines(content, tag)
    if start == -1:
        print(f"Tag '{tag}' not found in crontab.", file=sys.stderr)
        return 1

    # Backup before mutation
    backup = _backup_crontab(content)
    print(f"Backed up existing crontab: {backup}")

    lines = content.splitlines()
    removed = lines[start:end]
    remaining = lines[:start] + lines[end:]

    if args.dry_run:
        print("DRY RUN — would remove:")
        for line in removed:
            print(f"  {line}")
        return 0

    _install_crontab("\n".join(remaining) + "\n")

    # Verify removal
    new_content = _get_crontab()
    if tag not in new_content:
        print(f"Removed cron entry [{tag}]:")
        for line in removed:
            print(f"  {line}")
        return 0
    else:
        print("Error: tag still present after removal!", file=sys.stderr)
        return 1


def cmd_verify(args: argparse.Namespace) -> int:
    """Verify a tagged cron entry exists and its script is executable."""
    tag = args.tag
    content = _get_crontab()

    start, end = _find_tag_lines(content, tag)
    if start == -1:
        print(f"FAIL: tag '{tag}' not found in crontab.")
        return 1

    lines = content.splitlines()
    cron_line = lines[start + 1] if start + 1 < len(lines) else ""

    # Extract the command part (after 5 cron fields)
    parts = cron_line.split(None, 5)
    if len(parts) < 6:
        print(f"FAIL: malformed cron line: {cron_line}")
        return 1

    cmd_part = parts[5]
    # Extract the script path (first token, before any flags/redirect)
    script_path = cmd_part.split()[0] if cmd_part else ""

    checks = []

    # Check 1: cron entry exists
    checks.append(("cron entry exists", True, f"{cron_line}"))

    # Check 2: script file exists
    exists = Path(script_path).exists() if script_path else False
    checks.append(("script exists", exists, script_path))

    # Check 3: script is executable
    executable = os.access(script_path, os.X_OK) if exists else False
    checks.append(("script executable", executable, script_path))

    # Check 4: lockfile pattern in script
    has_flock = False
    if exists:
        text = Path(script_path).read_text()
        has_flock = "flock" in text
    checks.append(("has lockfile (flock)", has_flock, ""))

    # Check 5: log directory exists
    has_log = False
    if exists:
        has_log = "LOG_DIR" in text and "mkdir -p" in text
    checks.append(("has logging", has_log, ""))

    all_pass = True
    for name, passed, detail in checks:
        status = "PASS" if passed else "FAIL"
        if not passed:
            all_pass = False
        suffix = f" ({detail})" if detail else ""
        print(f"  [{status}] {name}{suffix}")

    return 0 if all_pass else 1


def cmd_generate_wrapper(args: argparse.Namespace) -> int:
    """Generate a headless Claude Code cron wrapper script."""
    name = args.name
    tag = name  # tag matches name
    # Sanitize prompt: replace any occurrence of the heredoc delimiter
    # to prevent heredoc injection if prompt contains 'PROMPT_END' on its own line.
    prompt = args.prompt.replace("PROMPT_END", "PROMPT_EN" + "D_ESC")
    workdir = args.workdir or os.getcwd()
    schedule = args.schedule
    budget = args.budget
    allowed_tools = args.allowed_tools
    logdir = args.logdir or f"{workdir}/cron-logs/{name}"
    output_dir = args.output_dir or f"{workdir}/scripts"

    script_name = f"{name}-cron.sh"
    output_path = Path(output_dir) / script_name

    if output_path.exists() and not args.force:
        print(
            f"Error: {output_path} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 1

    claude_path = _find_claude_path()

    content = WRAPPER_TEMPLATE.format(
        description=f"Claude Code headless cron: {name}",
        tag=tag,
        script_name=script_name,
        schedule=schedule,
        workdir=workdir,
        logdir=logdir,
        budget=budget,
        name=name,
        prompt=prompt,
        claude_path=claude_path,
        allowed_tools=allowed_tools,
    )

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    output_path.chmod(0o755)

    print(f"Generated: {output_path}")
    print(f"  Tag: {tag}")
    print(f"  Schedule: {schedule}")
    print(f"  Budget: ${budget}/run")
    print(f"  Claude: {claude_path}")
    print(f"  Logs: {logdir}")
    print(f"\nNext steps:")
    print(f"  1. Review: cat {output_path}")
    print(f"  2. Test:   ./{output_path}")
    print(f"  3. Install: python3 scripts/crontab-manager.py add \\")
    print(f"       --tag {tag} --schedule '{schedule}' \\")
    print(f"       --command '{output_path} --execute >> {logdir}/cron.log 2>&1'")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Safe crontab management for Claude Code cron jobs.")
    sub = parser.add_subparsers(dest="command")

    # list
    sub.add_parser("list", help="List crontab entries")

    # backup
    sub.add_parser("backup", help="Backup current crontab")

    # add
    p_add = sub.add_parser("add", help="Add a tagged cron entry")
    p_add.add_argument("--tag", required=True, help="Unique tag for this entry")
    p_add.add_argument("--schedule", required=True, help="Cron schedule (5 fields)")
    p_add.add_argument("--command", required=True, help="Command to run")
    p_add.add_argument("--dry-run", action="store_true", help="Show what would be added")

    # remove
    p_rm = sub.add_parser("remove", help="Remove a tagged cron entry")
    p_rm.add_argument("--tag", required=True, help="Tag to remove")
    p_rm.add_argument("--dry-run", action="store_true", help="Show what would be removed")

    # verify
    p_ver = sub.add_parser("verify", help="Verify a tagged cron entry")
    p_ver.add_argument("--tag", required=True, help="Tag to verify")

    # generate-wrapper
    p_gen = sub.add_parser("generate-wrapper", help="Generate a headless cron wrapper script")
    p_gen.add_argument("--name", required=True, help="Job name (used as tag + filename)")
    p_gen.add_argument("--prompt", required=True, help="Claude prompt text")
    p_gen.add_argument("--schedule", required=True, help="Cron schedule (5 fields)")
    p_gen.add_argument("--workdir", help="Working directory (default: cwd)")
    p_gen.add_argument("--budget", default="2.00", help="Max budget per run (default: 2.00)")
    p_gen.add_argument("--allowed-tools", default="Bash Read", help="Allowed tools (default: 'Bash Read')")
    p_gen.add_argument("--logdir", help="Log directory (default: workdir/cron-logs/name)")
    p_gen.add_argument("--output-dir", help="Output directory (default: workdir/scripts)")
    p_gen.add_argument("--force", action="store_true", help="Overwrite existing script")

    args = parser.parse_args()

    commands = {
        "list": cmd_list,
        "backup": cmd_backup,
        "add": cmd_add,
        "remove": cmd_remove,
        "verify": cmd_verify,
        "generate-wrapper": cmd_generate_wrapper,
    }

    if not args.command:
        parser.print_help()
        return 1

    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
