#!/usr/bin/env python3
"""Generate the human-readable static routing map (docs/routing-map.md).

Reads the same INDEX sources as routing-manifest.py (skills/INDEX.json,
agents/INDEX.json, pipeline-index.json) and writes a Markdown file with one
table per surface (AGENTS / SKILLS / PIPELINES). Every entry appears with ALL
triggers -- no TRIGGER_CAP truncation. The map is the full record; the
manifest is the runtime form.

Both are generated from frontmatter, so frontmatter is the single source of
truth.

Usage:
    python3 scripts/generate-routing-map.py            # write docs/routing-map.md
    python3 scripts/generate-routing-map.py --check    # exit 1 on findings
    python3 scripts/generate-routing-map.py --dry-run  # print to stdout

--check mode (exit 1 on any):
    - entry in INDEX missing from map (or stale row in map)
    - entry with empty description or zero triggers
    - a PUBLIC pairs_with name that resolves to nothing
    - committed docs/routing-map.md differs from a fresh render

Private components never reach the map. Names of locally installed private
components are removed from entries and from pairs_with lists before both
rendering and validation, using the same runtime source of truth as
hooks/pretool-private-name-leak-gate.py. A public name that resolves to
nothing is a real authoring error and is still reported.

Exit codes:
    0 -- generate succeeded, or --check found nothing
    1 -- --check found at least one finding
"""

from __future__ import annotations

import argparse
import functools
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAP_PATH = REPO_ROOT / "docs" / "routing-map.md"

# Single source of truth for "which component names are private". The leak
# gate derives the set at runtime from the local private-component tree; a
# second definition here would drift, and drift is the leak.
LEAK_GATE = REPO_ROOT / "hooks" / "pretool-private-name-leak-gate.py"

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))


def _index_paths(repo_root: Path) -> dict[str, Path]:
    return {
        "skills": repo_root / "skills" / "INDEX.json",
        "agents": repo_root / "agents" / "INDEX.json",
        "pipelines": repo_root / "skills" / "process" / "workflow" / "references" / "pipeline-index.json",
    }


def _ensure_generated_indexes(repo_root: Path) -> None:
    """Generate missing tracked indexes, or fail before rendering anything."""
    generators = {
        "skills": repo_root / "scripts" / "generate-skill-index.py",
        "agents": repo_root / "scripts" / "generate-agent-index.py",
    }
    for surface, index_path in _index_paths(repo_root).items():
        if index_path.is_file():
            continue
        generator = generators.get(surface)
        if generator is None or not generator.is_file():
            raise RuntimeError(f"required {surface} index missing and cannot be generated: {index_path}")
        subprocess.run([sys.executable, str(generator)], cwd=repo_root, check=True)
        if not index_path.is_file():
            raise RuntimeError(f"{generator.name} did not create required index: {index_path}")


HEADER = """\
<!-- Auto-generated by scripts/generate-routing-map.py — edit frontmatter, not this file. -->

# Routing Map

Single source of truth: agent/skill frontmatter and `pipeline-index.json`.
Regenerate: `python3 scripts/generate-routing-map.py`.
CI check: `python3 scripts/generate-routing-map.py --check`.
"""


def _escape_md(text: str) -> str:
    """Escape pipe characters for Markdown table cells."""
    return text.replace("|", "\\|").replace("\n", " ")


def load_all_entries(repo_root: Path = REPO_ROOT) -> dict[str, list[dict]]:
    """Load tracked entries from all three INDEX files, grouped by surface.

    The committed map must be identical across machines. Local index overlays
    contain private capabilities and therefore must never affect this artifact.
    """
    surfaces: dict[str, list[dict]] = {"agents": [], "skills": [], "pipelines": []}
    _ensure_generated_indexes(repo_root)
    for index_type, tracked in _index_paths(repo_root).items():
        try:
            raw = json.loads(tracked.read_text(encoding="utf-8"))
        except (FileNotFoundError, UnicodeError, json.JSONDecodeError, OSError) as exc:
            raise RuntimeError(f"required {index_type} index is unreadable or malformed: {tracked}: {exc}") from exc
        if not isinstance(raw, dict):
            raise RuntimeError(f"required {index_type} index root must be an object: {tracked}")
        items = raw.get(index_type)
        if not isinstance(items, dict):
            raise RuntimeError(f"required {index_type} index must contain an object at '{index_type}': {tracked}")
        for name, data in items.items():
            if not isinstance(data, dict):
                raise RuntimeError(f"required {index_type} index entry '{name}' must be an object: {tracked}")
            entry: dict = {
                "name": name,
                "description": data.get("description") or data.get("short_description", ""),
                "triggers": data.get("triggers", []),
                "force_route": bool(data.get("force_route", False)),
                "not_for": data.get("not_for", ""),
                "pairs_with": data.get("pairs_with", []),
            }
            surfaces[index_type].append(entry)
    return surfaces


@functools.lru_cache(maxsize=4)
def private_names(repo_root: Path = REPO_ROOT) -> frozenset[str]:
    """Lowercased names of locally installed PRIVATE components.

    Reuses the private-name leak gate's derivation
    (hooks/pretool-private-name-leak-gate.py), which builds the set at
    runtime from the local private-component tree and subtracts every
    public name. One definition of "private" in the toolkit, not two.

    Empty on any machine without a local private tree (CI, public
    installs). Nothing is private there, so nothing is filtered and the
    rendered map stays byte-identical across machines.
    """
    spec = importlib.util.spec_from_file_location("_private_name_leak_gate", LEAK_GATE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load the private-name source of truth: {LEAK_GATE}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return frozenset(module._private_names(repo_root))


def strip_private(surfaces: dict[str, list[dict]], private: frozenset[str]) -> dict[str, list[dict]]:
    """Drop private entries and private `pairs_with` names from surfaces.

    The map is a public artifact. A private name must never reach it, and
    its absence must not read as an authoring error, so the name is removed
    before both rendering and validation. Public names that resolve to
    nothing survive this filter and are still reported by --check.
    """
    if not private:
        return surfaces
    filtered: dict[str, list[dict]] = {}
    for section, entries in surfaces.items():
        kept: list[dict] = []
        for entry in entries:
            if str(entry["name"]).lower() in private:
                continue
            copy = dict(entry)
            copy["pairs_with"] = [p for p in entry.get("pairs_with", []) if str(p).lower() not in private]
            kept.append(copy)
        filtered[section] = kept
    return filtered


def _render_table(entries: list[dict]) -> str:
    """Render a list of entries as a Markdown table."""
    lines = [
        "| name | when to call (description) | triggers | FORCE | not_for | pairs_with |",
        "|---|---|---|---|---|---|",
    ]
    for e in sorted(entries, key=lambda x: x["name"]):
        name = _escape_md(e["name"])
        desc = _escape_md(str(e["description"]))
        triggers = _escape_md(", ".join(str(t) for t in e["triggers"]))
        force = "yes" if e.get("force_route") else ""
        not_for = _escape_md(str(e.get("not_for", "")))
        pairs = _escape_md(", ".join(str(p) for p in e.get("pairs_with", [])))
        lines.append(f"| {name} | {desc} | {triggers} | {force} | {not_for} | {pairs} |")
    return "\n".join(lines)


def generate_map(
    surfaces: dict[str, list[dict]] | None = None,
    private: frozenset[str] | None = None,
) -> str:
    """Generate the full routing map Markdown content."""
    if surfaces is None:
        surfaces = load_all_entries()
    if private is None:
        private = private_names()
    surfaces = strip_private(surfaces, private)
    parts = [HEADER]
    for section, label in [("agents", "AGENTS"), ("skills", "SKILLS"), ("pipelines", "PIPELINES")]:
        entries = surfaces.get(section, [])
        parts.append(f"## {label} ({len(entries)})\n")
        parts.append(_render_table(entries))
        parts.append("")
    return "\n".join(parts)


def _all_known_names(surfaces: dict[str, list[dict]]) -> set[str]:
    """Collect every name across all surfaces."""
    names: set[str] = set()
    for entries in surfaces.values():
        for e in entries:
            names.add(e["name"])
    return names


def check_map(
    surfaces: dict[str, list[dict]] | None = None,
    map_path: Path | None = None,
    private: frozenset[str] | None = None,
) -> list[str]:
    """Run --check validations. Returns a list of finding strings."""
    if surfaces is None:
        surfaces = load_all_entries()
    if private is None:
        private = private_names()
    surfaces = strip_private(surfaces, private)
    if map_path is None:
        map_path = MAP_PATH
    findings: list[str] = []
    known = _all_known_names(surfaces)

    for section, entries in surfaces.items():
        for e in entries:
            name = e["name"]
            desc = e.get("description", "")
            triggers = e.get("triggers", [])
            pairs = e.get("pairs_with", [])

            if not desc:
                findings.append(f"{section}/{name}: empty description")
            if not triggers:
                findings.append(f"{section}/{name}: zero triggers")

            for p in pairs:
                if p not in known:
                    findings.append(f"{section}/{name}: pairs_with '{p}' resolves to nothing")

    fresh = generate_map(surfaces, private=frozenset())
    try:
        committed = map_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        committed = ""
    if committed != fresh:
        findings.append("docs/routing-map.md is stale (differs from a fresh render)")

    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the static routing map.")
    parser.add_argument("--check", action="store_true", help="Validate the committed map; exit 1 on findings.")
    parser.add_argument("--dry-run", action="store_true", help="Print the map to stdout instead of writing the file.")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    parser.add_argument("--map-path", type=Path, default=None, help=argparse.SUPPRESS)
    args = parser.parse_args()

    map_path = args.map_path or (args.repo_root / "docs" / "routing-map.md")
    try:
        surfaces = load_all_entries(args.repo_root)
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    private = private_names(args.repo_root)

    if args.check:
        findings = check_map(surfaces, map_path, private=private)
        for f in findings:
            print(f"FINDING: {f}", file=sys.stderr)
        return 1 if findings else 0

    content = generate_map(surfaces, private=private)
    if args.dry_run:
        print(content)
    else:
        map_path.parent.mkdir(parents=True, exist_ok=True)
        map_path.write_text(content, encoding="utf-8")
        count = sum(len(v) for v in strip_private(surfaces, private).values())
        print(f"Wrote {map_path} ({count} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
