#!/usr/bin/env python3
"""
Validate that every component name in skills/meta/do/SKILL.md resolves.

The /do router's control law names skills, agents, and pipelines in its verb
maps, fallback clauses, error handling, and Phase 3 enhancement rows. A name
that resolves nowhere is a phantom route: the router selects it, the lookup
fails, and the request silently falls through to a generic handler. This
validator extracts candidate names from those regions and asserts each one
resolves in skills/INDEX.json, agents/INDEX.json, the pipeline index, or the
shared-patterns directory.

Scoped regions (anchor -> end anchor; a missing anchor is an error so file
restructuring cannot silently drop coverage):
  1. Step 0b (skill-greediness verb map + fallback clause)
  2. Step 2  (Common overrides verb map)
  3. Step 4  (Auto-Pipeline Fallback clause)
  4. Error Handling section
  5. Phase 3 ENHANCE section (enhancement + injection tables, prose rules)

Extraction contract (deterministic):
  - Fenced code blocks are skipped (pseudocode, shell).
  - Dotted paths/filenames are stripped (right-size-review.py, foo.md).
  - Candidates are lowercase hyphenated tokens: [a-z][a-z0-9]*(-[a-z0-9]+)+.
    Unhyphenated names (planning, quick, workflow) are indistinguishable from
    prose and out of scope; every audited phantom was hyphenated.

Resolution set:
  - skills/INDEX.json skill names (generated; run generate-skill-index.py)
  - agents/INDEX.json agent names (generated; run generate-agent-index.py)
  - skills/workflow/references/pipeline-index.json pipeline names
  - skills/shared-patterns/*.md stems (Phase 3 injection patterns)
  - BUILTIN_AGENTS: harness-provided agents outside agents/INDEX.json
  - voice-* names: voice profile skills generated by create-voice at the
    user level (~/.claude/skills/), never in the repo index
  - PROSE_TERMS: hyphenated English in the scoped regions, each justified.
    An entry with zero occurrences in the scoped regions is an error — a
    stale entry would let a future phantom silently reuse the name.

Exit codes:
  0 — every candidate resolves
  1 — phantom name(s) or stale PROSE_TERMS entry found (each printed), or a
      region anchor is missing

Usage:
    python scripts/validate-do-references.py [--skill-file PATH] [--repo-root PATH]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILL_FILE = REPO_ROOT / "skills" / "meta" / "do" / "SKILL.md"

# (region name, start anchor, end anchor). Matched as line prefixes after strip.
REGIONS = [
    ("step-0b-verb-map-and-fallback", "**Step 0b: Apply the routing decision**", "**Step 1.5:"),
    ("step-2-overrides", "**Step 2: Apply skill override**", "**Step 3:"),
    ("step-4-fallback", "**Step 4: Auto-Pipeline Fallback**", "**Lazy-completion"),
    ("error-handling", "## Error Handling", "## References"),
    ("phase-3-rows", "### Phase 3", "### Phase 4"),
]

# Harness-provided agents that exist outside agents/INDEX.json.
BUILTIN_AGENTS = frozenset({"general-purpose"})

# Voice profile skills are generated by create-voice into ~/.claude/skills/
# and indexed there, never in the repo index. Accept the name pattern.
VOICE_PROFILE_RE = re.compile(r"^voice-[a-z0-9]+(?:-[a-z0-9]+)*$")

# Hyphenated English inside the scoped regions. Each entry is prose, not a
# component name; a new entry needs the same justification.
PROSE_TERMS = frozenset(
    {
        "built-in",  # "built-in verification gates"
        "cross-repo",  # the [cross-repo] output tag
        "done-criteria",  # "Objective with done-criteria"
        "force-route",  # "force-route triggers"
        "near-matches",  # "check INDEX files for near-matches"
        "non-negotiable",  # "HARD — non-negotiable"
        "real-diff",  # "the real-diff row wins"
        "whole-repo",  # "whole-repo audits"
    }
)

# Dotted paths and filenames are file references, not routable components.
FILE_REF_RE = re.compile(r"[A-Za-z0-9_./{}-]*\.(?:md|py|js|mjs|json|jsonl|go|txt|yml|yaml)\b")

# Candidate component name: lowercase, at least one hyphen, standalone.
TOKEN_RE = re.compile(r"(?<![\w-])[a-z][a-z0-9]*(?:-[a-z0-9]+)+(?![\w-])")


def load_index(path: Path, key: str, hint: str) -> set[str]:
    """Return the top-level ``key`` dict's names from a JSON index file."""
    if not path.exists():
        print(f"ERROR: {path} not found — {hint}")
        sys.exit(1)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"ERROR: cannot parse {path}: {exc}")
        sys.exit(1)
    return set(data.get(key, {}))


def region_lines(lines: list[str], start: str, end: str, name: str) -> list[tuple[int, str]]:
    """Return (1-based line number, text) pairs between the two anchors."""
    start_idx = end_idx = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if start_idx is None and stripped.startswith(start):
            start_idx = i
        elif start_idx is not None and stripped.startswith(end):
            end_idx = i
            break
    if start_idx is None or end_idx is None:
        missing = start if start_idx is None else end
        print(f"ERROR: region '{name}' anchor not found: {missing!r} — update REGIONS to match the file")
        sys.exit(1)
    return [(i + 1, lines[i]) for i in range(start_idx, end_idx)]


def extract_candidates(pairs: list[tuple[int, str]]) -> list[tuple[int, str]]:
    """Return (line number, token) candidates, skipping fenced code blocks."""
    out: list[tuple[int, str]] = []
    in_fence = False
    for lineno, line in pairs:
        if line.strip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        cleaned = FILE_REF_RE.sub(" ", line).replace("/", " ")
        for token in TOKEN_RE.findall(cleaned):
            out.append((lineno, token))
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate component names in the /do control law.")
    parser.add_argument("--skill-file", type=Path, default=SKILL_FILE, help="Path to skills/meta/do/SKILL.md")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT, help="Repo root holding the INDEX files")
    args = parser.parse_args()

    root = args.repo_root
    gen_hint = "generated file; run: python scripts/generate-skill-index.py && python scripts/generate-agent-index.py"
    skills = load_index(root / "skills" / "INDEX.json", "skills", gen_hint)
    agents = load_index(root / "agents" / "INDEX.json", "agents", gen_hint)
    pipelines = load_index(
        root / "skills" / "workflow" / "references" / "pipeline-index.json",
        "pipelines",
        "checked-in pipeline index",
    )
    shared_patterns = {p.stem for p in (root / "skills" / "shared-patterns").glob("*.md")}
    resolvable = skills | agents | pipelines | shared_patterns | BUILTIN_AGENTS | PROSE_TERMS

    if not args.skill_file.exists():
        print(f"ERROR: skill file not found: {args.skill_file}")
        return 1
    lines = args.skill_file.read_text(encoding="utf-8").splitlines()

    checked = 0
    seen: set[str] = set()
    offenders: list[str] = []
    for name, start, end in REGIONS:
        for lineno, token in extract_candidates(region_lines(lines, start, end, name)):
            checked += 1
            seen.add(token)
            if token in resolvable or VOICE_PROFILE_RE.match(token):
                continue
            offenders.append(
                f"PHANTOM: '{token}' ({name}, line {lineno}) — resolves in no index"
                " (skills/INDEX.json, agents/INDEX.json, pipeline-index.json, shared-patterns)"
            )

    for term in sorted(PROSE_TERMS - seen):
        offenders.append(
            f"STALE ALLOWLIST: '{term}' in PROSE_TERMS has zero occurrences in the scoped regions"
            " — remove it so a future phantom cannot silently reuse the name"
        )

    for msg in offenders:
        print(msg)
    if offenders:
        print(f"\n{len(offenders)} violation(s) in {args.skill_file} — every routed name must resolve.")
        return 1
    print(f"OK: {checked} component-name mentions checked in {len(REGIONS)} regions; all resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
